export * from 'lodash-es';
export * from './isEvalError';
export * from './isFloat';
export * from './isRangeError';
export * from './isReferenceError';
export * from './isSyntaxError';
export * from './isTypeError';
export * from './isURIError';
export * from './isValidDate';
