name: sync

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        with:
          source-repo: git@github.com:ModyQyW/utils.git
          destination-repo: git@gitee.com:ModyQyW/utils.git
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
